env:
  browser: true
  es2021: true

root: true

extends:
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:import/recommended
  - plugin:jsx-a11y/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended

overrides: []

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - '@typescript-eslint'

rules:
  {
    no-console: 0,
    no-param-reassign: 0,
    react/prop-types: 0,
    import/extensions: ['error', 'never'],
    functional/no-conditional-statement: 0,
    functional/no-expression-statement: 0,
    functional/immutable-data: 0,
    functional/functional-parameters: 0,
    functional/no-try-statement: 0,
    functional/no-throw-statement: 0,
    no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }],
    react/function-component-definition: [2, { 'namedComponents': 'arrow-function' }],
    testing-library/no-debug: 0,
    react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx'] }],
    jsx-a11y/click-events-have-key-events: off,
    jsx-a11y/no-noninteractive-element-interactions: off,
    jsx-a11y/no-static-element-interactions: off,
    react/jsx-props-no-spreading: 0,
    react/no-array-index-key: 0,
  }
